### ISSUE TITLE
Problem in simulating MS-DSGE model

### ISSUE THREAD

**Issue by Moyan96** [jmaih/RISE_toolbox#103]
Hi Junior:
I have a problem using the TaoZha/DSGE/torial 3. I built my own model and used my own data to estimate. When I wanted to conduct MCMC using code as follows:

parfor imod=1:nmodels
    % replace "for" by "parfor" if you want to use parallel computation
    disp('*--------------------------------------------------------------*')
    disp(['*----------- MCMC for ',model_names{imod},' model-------------*'])
    disp('*--------------------------------------------------------------*')
    % Here the simulations are stored in variable, which here we call
    % postSims.
    %-----------------------------------------------------------------
    [objective{imod},lb{imod},ub{imod},x0,SIG]=pull_objective(estim_models{imod});
    
    Results{imod}=mh_sampler(objective{imod},lb{imod},ub{imod},mcmc_options,x0,SIG);
    
matlab prompted me that 'the matrix must be a positive definite matrix'. I wondered what went wrong.

//错误使用 mh_sampler>do_one_chain/scale_times_sqrt_covariance_updating (line 480)
//矩阵必须为正定矩阵。(the matrix must be a positive definite matrix)

//出错 mh_sampler>do_one_chain (line 283)
//scale_times_sqrt_covariance_updating()

//出错 mh_sampler (line 106)
//parfor(ichain=1:nchain,nworkers)

Moyan,
2019.3.12

**Comment by jmaih** [comment]
Hi Moyan,

The problem you are facing is pretty common. The optimization in the
previous step did not result in a clean mode with a positive definite
covariance matrix. In that case the covariance matrix used for computing
MCMC is not valid. The procedure requires a positive definite covariance
matrix.

There are several remedies to that problem, none of which is perfect:

   1. Use any positive covariance matrix and possibly add the an option to
   adapt it on the fly (check the help for mh_sampler)
   2. cure the current covariance matrix, forcing it to be positive
   definite and then use it in the mcmc procedure, and definitely use the
   option to adapt it. You could cure a covariance matrix by using the routine
   utils.cov.nearest. You call it as C=utils.cov.nearest(C)
   3. use an optimizer that has better exploitation capabilities so that,
   hopefully, it climbs higher than your current mode and produces a
   covariance matrix with the desired properties.

Cheers,

Junior

**Comment by Moyan96** [comment]
Junior:
I found some problems in the model I set, and Matlab suggested that the matrix was close to the singular value. So I modified my model and solved the problem successfully. Thank you for your time.

Regards,
Moyan

**Comment by jmaih** [comment]
Moyan

Thanks for letting me know. 

Cheers

Junior
