### ISSUE TITLE
Prior specification

### ISSUE THREAD

**Issue by dingliumath** [jmaih/RISE_toolbox#107]

**Comment by dingliumath** [comment]
Hi Junior,
I am seeking your help again. I have been playing estimating an optimal policy problem under commitment. Unfortunately, a "Matrix is close to singular or badly scaled" problem occurred.  I am thinking of modifying the prior distributions, since I noticed that the prior mean and standard deviation for some parameters are NaN. However, I am not sure about syntax for specifying priors. So far, I am simply following the examples in the RISE toolbox.  Could you please give some more details on this?

For example,  what are the meaning for each value below? 
sigma_a,  0.5,0.01,2,  inv_gamma_pdf(0.9); 

I think it reads: Initial Value=1.5, Lower Bound=0.01, Upper Bound=2.
However, this specification leads to NaN prior means and standard deviation. 

Cheers,
Ding

**Comment by jmaih** [comment]
Hi Ding,

It seems that you are making good progress.

Did the problem of the matrix being close to singular or badly scaled occur
during estimation or during another process?

The prior mean and standard deviations can only be nan if you set them so
or do something stupid (no offence).

In RISE when you write,  sigma_a, 0.5,0.01,2, inv_gamma_pdf(0.9); you mean
that there is a 90% probability that the parameter is between 0.01 and 2

On the other hand, if you write sigma_a, 0.5,0.01,2, inv_gamma_pdf; At that
moment you imply that the distribution has mean 0.01 and standard deviation
2.

Cheers,

Junior

**Comment by dingliumath** [comment]
Hi Junior, 
Thanks a lot for your reply. No offense taken. 
The problem of the matrix being close to singular or badly scaled occurred during calling mh_sampler after the estimation. The matrix estimation.posterior_maximization.vcov is ill-conditioned. 

What puzzles me is that I did not set the prior mean or std dev of sigma_a to be NaN, even though RISE returns NaN in the estimation.prior field. The model details and estimation results (pboc_commitment.mat) are given in the attachment. We get NaN for the prior means and std dev of sigma_a, sigma_delta and sigma_mu. Perhaps you can help me out. 
[junior.zip](https://github.com/jmaih/RISE_toolbox/files/3003711/junior.zip)

By the way, can we specify priors in RISE as in dynare in the following format (or something equivalent):
PARAMETER_NAME, INITIAL_VALUE,LOWER_BOUND, UPPER_BOUND,PRIOR_SHAPE,PRIOR_MEAN, PRIOR_STANDARD_ERROR,PRIOR_3RD_PARAMETER,PRIOR_4TH_PARAMETER
or 
PARAMETER NAME, PRIOR SHAPE, PRIOR MEAN, PRIOR STANDARD ERROR, PRIOR 3rd PARAMETER ,PRIOR 4th PARAMETER

Cheers,
Ding

**Comment by jmaih** [comment]
Hi Ding,

I do not have lots of extra time on hands at the moment. Look into other
examples in the examples folder to see how priors are set.

In RISE you can only specify priors in the way RISE understands:
- either using quantiles
- or using mean and standard deviations

The first approach is more flexible.

The problem of the singular covariance matrix that occurs is quite common
and may not have anything to do with the priors. If the posterior
maximization steps has not reach a maximum or if some parameter lies up
against the boundaries of the parameter space, this problem will occur.

In order to do MCMC, stricly speaking you don't need the covariance matrix
that comes from posterior maximization. All you need is a positive defnite
matrix of appropriate format.

The sampler that you are using allows the updating of the covariance matrix
and so if you choose the option of updating the covariance matrix, you can
essentially start with any covariance matrix. Check the help for mh_sampler.

I am afraid I might not have time to answer further questions for now. I
have some deadline approaching real fast and I have to finish up something.

Cheers,

Junior

**Comment by dingliumath** [comment]
Hi Junior,
Thanks a lot for your time and advice.  
Cheers,
Ding
