### ISSUE TITLE
2nd vs 1st Order Simulation - Different Steady States?

### ISSUE THREAD

**Issue by otavio1teixeira** [jmaih/RISE_toolbox#117]
Hello, Mr. Maih and RISE Community. 
I have a simple New Keynesian model with two exogenous switching regimes. The model is nonlinear. When I do 1st order simulation, everything goes as expected, i.e., I can replicate the 1st order IRFs. Yet, when it comes to 2nd order simulation, my variables converge to a different steady state, even when I set all shocks to zero and fix the regime path at, say, regime 1. In this case, I would expect all variables to stay put, which is not happening.

I feel like missing something pretty obvious, so I'm sorry if the question is too basic
My codes are attached. Running "Run_Simulation" should replicate the weird result I mentioned above.

Thank you very much for your patience and, once again, congratulations for the really great job!
Greetings from Brazil.

[Simulation.zip](https://github.com/jmaih/RISE_toolbox/files/3668501/Simulation.zip)

**Comment by jmaih** [comment]
Hi Otavio,

Sorry for the delay. Will you, please, tell me whether you are using the current online version of RISE or another?

Thanks,
J.

**Comment by otavio1teixeira** [comment]
Hello,
I am using a version downloaded on March 2019.
To make sure the RISE version is not an issue, I've just downloaded the latest version of RISE and ran my files again. The behavior of simulations remains exactly the same as before.
Any clue on what may be causing these results?

Thank you for your response, I really appreciate.
Otávio

**Comment by jmaih** [comment]
Hi Otavio,

   1. Because of the fact that the second-order approximation is
   non-certainty equivalent, which implies that there is a nonzero
   contribution of the perturbation parameter, a simulation without shocks
   will not return to the deterministic steady state. Rather, the process will
   move towards the stochastic steady state.
   2. If you want to return to the deterministic steady state, you will
   need to kill of the effect of the perturbation parameter by setting option
   "simul_sig" to 0.
   3.  The pruning algorithm in the version you are using needs to be
   updated.

There was no need to download the latest version online. What I wanted to
know was just whether you were using code downloaded online or not.  There
is a totally different version of RISE in the works, I will be pushing it
online at some point.

May I ask how long you've been using RISE and whether you know lots of
other people using it?

Cheers,

J.

**Comment by otavio1teixeira** [comment]
Thank you for the clarification. It makes sense now. Turning 'simul_sig' to 0 delivers what I needed. Also, thank you for the information about the pruning algorithm and the to-be-released version of RISE.

For those reading this post, a fruitful discussion on the stochastic steady state can be found on issue #113 - Stochastic steady state with RISE?

Regarding your last question, I've been using RISE since the beginning of the year (2019). I am using the toolbox in my master thesis, and I intend to keep using during my PhD. When I finish writing it I will send to you some interesting results.

In my faculty (FGV-EESP, in Brazil) I am the first to use RISE to write a master or PhD thesis. Professors here had never heard of the toolbox before. I also spoke to some friends at Rio de Janeiro (PUC-RJ) and one professor there, which was at the Central Bank at the time, knew about it, but had never used it. For the time being not many people use it around here (unfortunately).

Maybe in the Brazilian Central Bank there are people that use it, since they have a big team focused on DSGE modeling. But this is only a guess.

Finally, I support Junior Maih for Nobel Prize 2019! To be released in a couple of weeks... Thank you very much for your superhuman patience.

Best,
Otavio

**Comment by jmaih** [comment]
Hi Otavio,

Thanks for the kind words and for your wish for me to win the Noble Prize. Should that ever come to pass, I will remember you were one of the few who foresaw it :)

Cheers,

J.
