### ISSUE TITLE
Changing options for optimizer.

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#12]
Hi Junior,
I would like to make MaxTime value higher, since I have a filling that the mode I found is not the right one.  But I don't succeed in doing that.  In the 'help' I read that we can specify a cell, containing the name of the optimizer and other inputs. So I do: 
optimpot=struct('MaxNodes',20,'MaxIter',1000,'MaxTime',3600*5,...
     'MaxFunEvals',inf);

 X = java_array('java.lang.String', 7);
X(1) = java.lang.String('bee_gate');
X(2) = java.lang.String('fh');
X(3) = java.lang.String('x0');
X(4) = java.lang.String('lb');
X(5) = java.lang.String('ub');
X(6) = java.lang.String('optimpot');
X(7) = java.lang.String('varargin');

My_optim = cell(X)

estim_models_3=estimate(estim_models_3,'optimizer',My_optim); 

Could you please tell me what is the right way of doing it? Shall I right a wrapper to change the initial settings?

Thanks in advance!

**Comment by AnasZa** [comment]
Sure I could change directly in estimation_engine.m, but I guess there should be other way.

**Comment by jmaih** [comment]
Hi Anastasia,

It is ALWAYS a bad idea to try to hack RISE. This is because of the programming paradigm RISE subscribes to. I showed you last time how to design your own optimizer so that it is compatible with RISE. The same principles extends to solution algorithms, filters and so on. So I would strongly advise against going into estimation_engine.

RISE does not need to know the details of your optimizer, solver, filter, etc. so long as your function admits the inputs and the outputs that RISE expects.

What optimizer exactly do you want to use? Not all optimizers work with MaxTime.

You don't need to start going into java and so on, it is much simpler than that. The way to pass options to standard Matlab optimizers as well as the ones included in RISE is through the option 'optimset'. For example

```
myoptim=struct('MaxTime',3600*12,'MaxFunEvals',inf,'MaxIter',inf);

m=estimate(m,'optimizer',yourRoutine,'optimset',myoptim)
```

cheers,

J.

**Comment by AnasZa** [comment]
Thanks a lot. I did try what you suggested before, but instead of 'optimset', I put 'options' and of course it didn't work.
