### ISSUE TITLE
Reporting number of iteration in the optimizer

### ISSUE THREAD

**Issue by tonyxia324** [jmaih/RISE_toolbox#122]
Hello Junior,

I'm running a loop that estimates the same model several times just to check whether my estimation results can be replicated. I have found that sometimes the optimizer(bee_gate) reports the following:
![image](https://user-images.githubusercontent.com/31831361/67400188-e03b3700-f5df-11e9-83b5-80269cf7298a.png)

I think this is due to the optimizer having difficulty finding the local maximum. I know that the max iteration can be adjusted by the option 'MaxIter'. Is there a way to report the number of iterations done by the optimizer during the estimation process and save it in the Matlab workspace?

Also, if the optimizer stops due to the number of iterations reaching some upper bound, will RISE report some results based on the incorrect solution from the optimizer?

Best regards,
Tony

**Comment by jmaih** [comment]
Hi Tony,
1-) set debug to false to avoid printing 7 0 7
2-) you can certainly adjust the number of iteration of bee_gate. Personally I usually set it to infinity and rather put an upper bound on maxTime, the amount of time to use for searching. 
3-) unless you find the global peak for each run or you explicitly set a seed or you use a deterministic solver, your results are not expected to be replicable in general since bee_gate is a stochastic search-type of optimization procedure.
4-) the results are always reported at the point where optimization stops. 

Cheers,

J. 

Sendt fra min iPhone

**Comment by tonyxia324** [comment]
Hello Junior,

Thank you for the feedback. I have added the 'debug' option as follows and it doesn't seem to work:
[estim_models{1},filtration{1}]=estimate(estim_models{1},'optimizer','fmincon','optimset',myoptim,'debug',false);

I still have a lot of 7 0 7 printed on Matlab. I have attached my code below for your reference.  Thank you!
[model.zip](https://github.com/jmaih/RISE_toolbox/files/3765335/model.zip)

Best regards,
Tony

**Comment by jmaih** [comment]
Please let me know if this is still an issue.
