### ISSUE TITLE
Posterior Samlping 

### ISSUE THREAD

**Issue by xiongcheneco** [jmaih/RISE_toolbox#125]
Dear Junior,
When I run the Metropolis hastings algorithm to sample from the posterior distribution,  I found that
stderr of shocks are very large, most of them are bigger than 2. The 90%  range of prior distribution is [0.001, 1].
I want to know what is the most likely cause ?
Many thanks !
Best,
Chen

**Comment by jmaih** [comment]
Hi Chen,

If the 90% range of the prior distribution is the one you specified, then
it is not surprising to me that you find estimates of the standard
deviation that are larger than 2. Your prior distribution does not prevent
the estimates from going beyond 2. It also means that the estimation
prefers larger stderr rather than smaller ones or in other words the
endogenous dynamics of your model does not explain the data well enough to
estimate low values of standard deviation of the shocks.

Cheers,

J.

**Comment by xiongcheneco** [comment]
Dear Junior,
Thank you for your response. Even when the 90% range of the prior distribution is 0.1, stderr is still very large.  You think the  possible reason is  that my model does not explain the data well enough, but when I do estimation, I can get a relatively well result and the model can explain the data well.
Is there any other possible reason ?
Many thanks !
Best,
Chen

**Comment by jmaih** [comment]
Please let me know whether there's still an issue here
