### ISSUE TITLE
Initial values for estimated parameters

### ISSUE THREAD

**Issue by AnasZa** [jmaih/RISE_toolbox#13]
Dear Junior,

Every time I start estimate I get the message:

"Looking for good enough start values. Please wait..."

Isn't it enough to precise the starting value while defining my priors?

Anyway, I would like to give initial values for estimated parameters. I tried :

the_mod_file =  struct('param_nk_1', 0.18, 'param_nk_2', 0.55);
m=estimate(m,'optimizer','bee_gate','optimset', myoptim,'estim_start_vals', the_mod_file); 

But I get an error: 

Error using rise_generic/set/set_one_at_a_time (line 139)
the_mod_file' is not a settable option or property of class rise

Error in rise_generic/set (line 116)
set_one_at_a_time();

....

What is the right way of doing it? 
Thanks in advance.

**Comment by jmaih** [comment]
1. You've already given some start values in specifying the priors. There is no need to look any further.

2. if you use bee_gate, that optimizer needs more starting values than the single one you provided. In fact, it needs 'MaxNodes' starting values and the default is 20. If the start value you provided is a good one, RISE will need in this case another 19 points.

3. More generally, if you use bee_gate or any other stochastic optimizer of RISE, or the initial value for estimation you provided is very unlikely, RISE will look for "a good place to start".

4. if optimization has a hard time starting, this is a sign that you have to check your model or the setup of estimation. One thing that can often occur, especially in regime switching models, is that the initial covariance matrix at which to initialize the filter does not exist. In this case, one thing that can help is to use a diffuse prior, which is implemented in RISE under option kf_init_variance. You have to set this option to some arbitrary number e.g. 

```
'kf_init_variance', 5 
```

and add a presample in order to avoid adding the initial observations to the likelihood 

```
'kf_presample', arbitraryInteger
```

where in a sense, "arbitraryInteger" is the number of periods over which you initialize the filter.

J.

**Comment by AnasZa** [comment]
Thank you very much for the useful advice.

But say, I estimate with my optimizing routine (the one you wrote for me)  csminwelwrap
 that is using sims’ optimizer. And I got my mode x1. But then I would like to use fmincon to check but starting from the previous mode. What shall I do in this case?

 I know there is an option estim_start_from_mode, but it is not clear which file it takes. What if I rename my model… How can I precise the file myself?

**Comment by jmaih** [comment]
Hopefully I understand a little better what your problem is.

The mode is stored inside the object itself and so there is no need to look for a file.

Just set 

```
'estim_start_from_mode', true
```

of course do not forget to change the name of the optimizer

```
m_new=estimate(m_old,'optimizer','fmincon','estim_start_from_mode', true)
```

where m_old is the model object with the old estimation

Cheers,

J.

**Comment by AnasZa** [comment]
I think I am not clear enough. Yes, 'estim_start_from_mode', true - option I already tried. But it is not always possible. 

Say I my estimation crashed. The mode is not saved but  I can see the last values (there is this matrix that appears with each iteration), say vector x1. So How can I tell RISE to use it knowing that it is not stored inside the object itself? 

Thanks!
A

**Comment by jmaih** [comment]
I would just put whatever x1 you have in the same place where you defined your priors in the first place.

You may want to note that you don't need to define your priors inside the model file. They can be set outside and be manipulated with ease, just pushing whatever result you get into the model object using a statement like

```
m=set(m,'estim_priors',yourPriors)
```

J.
