### ISSUE TITLE
Creat new objects parameterized with posterior mean

### ISSUE THREAD

**Issue by Kairey** [jmaih/RISE_toolbox#134]
Dear Maih,
With the illumination of issue #80 , I know how to creat new objects parameterized with randomly drawed parameter set by running "[draw,m1]=draw_parameter(m0,Results.pop)", or parameterized with the best drawed parameter set by running "[draw,m1]=draw_parameter(m0,Results.pop(best))". 
My question is, after implement MCMC sampling, how can I creat new objects parameterized with other parameter sets, such as the having computed posterior mean parameter set called "Mean", or some other self-defined parameter sets?
Best,
Kairey

**Comment by jmaih** [comment]
Hi,

You parameterize a model using the samples you obtained from the MCMC procedure. You cannot parameterize the model with the mean or any other quantile of the parameters. This is in part because those quantiles need not be valid parameter vectors. 

If, say, you want to compute the mean of the impulse responses, the way to go about it is to compute impulse responses for many parameterizations of the model and then average those impulse responses.

This is the way to go about it for any other statistic you have in mind.

Cheers,

J.
