### ISSUE TITLE
A problem about the estimation results

### ISSUE THREAD

**Issue by PeeBar** [jmaih/RISE_toolbox#141]
Hi dear Mr. Maih:
I used RISE to estimate my own DSGE model. The estimated results are [here](https://github.com/PeeBar/RISE_ATTEMPT/blob/master/results.png).
Obviously the results are wrong because the 'mode std' results are not real numbers, this is unreasonable. I don't know where is wrong and I have no idea how to debug this problem. Could you please have a look if time allows? 
Thank you very much.
sincerely
Xu

**Comment by jmaih** [comment]
Hi,

This happens when the optimizer stops before reaching a peak. The covariance matrix at that point is not positive definite and this is why the standard deviations are complex numbers.

You may want to change the optimizer if you have a better one or change the problem (e.g. have more informative priors) so that the optimizer reaches a peak.

But a more important question is what you need the standard deviations for. If you would like to perform posterior sampling, strictly speaking you do not need the covariance matrix that arises from posterior optimization. In this case you can either "correct" the covariance matrix or get a new one that you can, possibly, update as you sample the posterior distribution. For this purpose it is therefore not necessary to have a well defined covariance matrix, it is not even necessary to do posterior maximization in the first place.

Now if you want to interpret the standard deviations at the mode, that's a different story. In that case you really need a problem and an optimizer that are such that you reach a peak after posterior maximization.

Cheers,

J.

**Comment by PeeBar** [comment]
Thank you for your response! You're so kind!
Best
Xu.
