### ISSUE TITLE
Estimation with singularity and bad scale

### ISSUE THREAD

**Issue by paul9255** [jmaih/RISE_toolbox#142]
Dear Junior Maih:
Please forgive me for bothering you. I used the RISE to solve my constant MS-DSGE model. And I got a warming message:
"Matrix is close to singular or badly scaled. RCOND =  3.872922e-33.
In generic_tools.posterior_maximization_variable_quantities (line 50)
In generic/estimate (line 329)
In dsge/estimate (line 47)
In Constant_zhu (line 85)"
Based on solves of other issues with singularity and bad scale proposed in the forum, I tried to solve the issue by adding stderr_ and reseting parameters. However, the problem still cannot be solved. Could you tell me why I got the message? And how to modify it?
Here is my code:
[paul.zip](https://github.com/jmaih/RISE_toolbox/files/4980930/paul.zip)

Many thanks!
Paul

**Comment by jmaih** [comment]
Hi Paul,

The singularity is not related to the measurement errors. It arises from the computation of the covariance matrix at the end of the posterior maximization process. Unfortunately the optimizer you are using doesn't reach a well-defined peak and as a result, the computed covariance matrix is not positive definite. 

This problem may arise either because of a poor performance of the optimizer or because some estimated parameter lies up the boundaries of the parameter space. 

Potential solutions include changing the priors so as to prevent estimation from hitting the boundaries, changing the optimizer, perhaps starting from a different initial condition.

Cheers,
J.
