### ISSUE TITLE
Problem solving the model

### ISSUE THREAD

**Issue by DayAfterDayAfterDay** [jmaih/RISE_toolbox#186]
Dear Prof. Maih,
I'm trying to solve and estimate a small DSGE and I'm having problems trying to figure how to calculate the policy function of a variable, the variable is defined as follows m{+1} = exp(-(1/theta)*V{+1})/E[exp(-(1/theta)*V{+1})],  it should be the ratio between the exponential of the variable (without expectation) and the expected value of the same transformation.
How can I do something like this?
Also I the model has an occasionally bindng constraint on debt (with associated multiplier mu) but I don't want the constraint to be governed by the switching mechanism, can you tell me if the code I have written it's right?
Thanks in advance for your help.
[ambig.txt](https://github.com/user-attachments/files/15644097/ambig.txt)

Andrea

**Comment by jmaih** [comment]
Hi Andrea,

You can break the problem into several parts using auxiliary variables.

AUX{t}= E[exp(-(1/theta)*V{+1})]

m{+1} = exp(-(1/theta)*V{+1})/AUX{t};

That said, I am not sure whether what you want to do is correct anyway.
check whether the left-hand side is dated t or t+1.

Cheers,

J.

**Comment by DayAfterDayAfterDay** [comment]
Dear Prof. Maih,

Thank you very much for your answer! What I need to calculate is just the ratio between the exp transformation of the random variable V and the expected value of the same quantity both in t+1 which is the definition of m{+1}, but more in general, it's possible to explicitly as RISE to calculate the conditional expectation E_t [V]? So that I can calculate m = exp(-(1/theta)*V) / E_t [exp(-(1/theta)*V)].

Thank you again for your help!

Andrea

**Comment by jmaih** [comment]
V{+1}  is interpreted as E_t(V{+1})I don’t know whether that’s what you mean. 6. juni 2024 kl. 23:22 skrev Andrea Fratini ***@***.***>:﻿
Dear Prof. Maih,
Thank you very much for your answer! What I need to calculate is just the ratio between the exp transformation of the random variable V and the expected value of the same quantity both in t+1 which is the definition of m{+1}, but more in general, it's possible to explicitly as RISE to calculate the conditional expectation E_t [V]? So that I can calculate m = exp(-(1/theta)*V) / E_t [exp(-(1/theta)*V)].
Thank you again for your help!
Andrea

**Comment by DayAfterDayAfterDay** [comment]
Dear Prof. Maih,
Thank you, that's the problem that I have, I need to calculate just the ratio between the random variable and its conditional expectation, is it possible to do in t instead of t+1? 

Thanks!

Andrea

**Comment by jmaih** [comment]
I am not sure I understand. E_t(V{t}) = V{t}Please express the mathematical problem more clearly.J. 6. juni 2024 kl. 23:47 skrev Andrea Fratini ***@***.***>:﻿
Dear Prof. Maih,
Thank you, that's the problem that I have, I need to calculate just the ratio between the random variable and its conditional expectation, is it possible to do in t instead of t+1?
Thanks!
Andrea
