### ISSUE TITLE
Problems in RS-DSGE model settings

### ISSUE THREAD

**Issue by Darson666** [jmaih/RISE_toolbox#192]
Hello Prof. Maih,
I encountered a problem while trying to endogenize the state transition probabilities. In the paper, the state transition probabilities are represented in the following form, but it seems that the RISE does not support integral operations. I would like to know how to define this form of state transition probabilities in RISE

![1733577612681](https://github.com/user-attachments/assets/d722fbdd-fa41-4a7f-b00f-b48810c6afcb)

**Comment by jmaih** [comment]
Hi Ekko_cool,

You should write a function that solves the integral yourself and pass it
to RISE as an alien function.

The function should compute the integral and its derivatives. The function
should be written so that it is possible to call it in two different ways:
x=f(a1,a2,...,an)
x=f(a1,a2,...,an,'diff',der)
where :
• x is the output of the function
• a1, a2, . . . , an: are the main inputs of the function
• ‘diff’ is an input that signals that triggers the computation of
derivatives
• der is a scalar of or a 1 x k vector specifying the derivatives
requested. The number of elements, k, in der is the
order of differentiation. The numbers in the vector are the locations of
the elements to differentiate. E.g:
– x=f(a1,a2,. . . ,an,’diff’,1) : first-order derivative wrt first argument
– x=f(a1,a2,. . . ,an,’diff’,[1,2]) : second-order derivative wrt arguments
1 and then 2
–etc.
