### ISSUE TITLE
Plotting posteriors after mh_sampler

### ISSUE THREAD

**Issue by tompiechula** [jmaih/RISE_toolbox#25]
Dear Junior,
I am trying to estimate the parameters for my MSDSGE model but when I try to use the plot_posteriors funtion, after the MH algorithm stops I get this error:

Error using matlab.graphics.axis.Axes/set
While setting the 'XLim' property of 'Axes':
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf

For some starting points it is ok, but for others the error message pops up. Are there any additional settings that can change the limits of the axis?

Thank you,
Tom

**Comment by jmaih** [comment]
Hi Tom,

1. Are you using a recent version of RISE or an old one? If you are using an old one, you may want to update RISE and check whether you still face the same problem.

1. Does this happen with a specific parameter or with all of them? you can plot one particular parameter by running `plot_posteriors(m,simulation_folder,'alpha')`, where m is your model object, simulation_folder is the location of draws or the draws themselves and alpha is the name of the parameter you want to plot. If you want to plot many parameters, say alpha and beta, you would replace the statement above with `plot_posteriors(m,simulation_folder,{'alpha','beta'})`

1. Could it be the case that there is not enough variation in the parameter after posterior simulation? Instead of having RISE plot the parameter for you, you can request the data for the plot so that you may plot the posterior yourself. To do this, call the function with one output variable, e.g. `pdata=plot_posteriors(m,...)` . you can then inspect the data returned by RISE and perhaps get an insight into the reasons for the crash.

1. If none of the things above works, maybe you can pause the execution of the function at the point where it crashes, save the workspace and send it to me by email?

Cheers,

Junior

**Comment by tompiechula** [comment]
Thank you Junior for your answer. I tried to do some of the plots and it worked. And you are right - sometimes there is not enough variation in the parameters. However, I still cannot fit the model to the data after many trials with fmincon and bee_gate. I have a slightly modified model from rwz2012 with Markov Switching from the examples.
Does RISE have some other optimizers apart from fmincon and bee_gate? I mean the global ones.

Thank you,
Tom

**Comment by jmaih** [comment]
Hi Tom,

Estimation is a much more difficult business than people typically assume. Fmincon, the default optimizer in RISE, is a dervatives-based optimization procedure. It will be fast and reliable for smooth problems with unique peak. When those conditions are not satisfied as it is almost always the case for the type of models we analyze (unless one uses tight priors), anything can happen:

- The optimization may not converge to a minimum
- The optimization may converge to a local minimum in the presence of multimodality.

RISE allows the user to use their own optimization procedure as long as it is available on the matlab path and as long as it accepts a specific number of inputs (in a specific order) and returns the outputs that RISE expects. Check the help `help dsge/estimate` and check out the following threads #12, #21 .

bee_gate is a stochastic optimization procedure and it is derivative free. It has superior exploration capabilities than dervative-based methods. The cost to pay is that it has inferior exploitation capabilities: even if it is very close to a peak, it may take a long time to get there. Therefore, bee_gate should be run for a long time.

 I assume you used bee_gate with its default settings? It is in fact a very complicated optimizer with perhaps too much flexibility. You can have it run for any amount of time, any number of function evaluations or any number of iterations you choose. You can even pause or stop the execution of the optimization process without losing your results.

Cheers,

Junior

**Comment by tompiechula** [comment]
Thank you for your reply. I used both fmnicon and bee_gate but there seems to be a problem with my model as some changes made the estimation possible. And yes, I did not expect the estimation to be so demanding :)
Best,
Tom
