### ISSUE TITLE
about implementing csminwel or a more efficient optimization algorithm

### ISSUE THREAD

**Issue by Pedro0304** [jmaih/RISE_toolbox#26]
Hi Junior,

I have replicated one example from Dynare in RISE but i got serious problems during the estimation,
the think is that dynare reaches a global minimum (while reaching the posterior mode) which is lower than the one i got from rise, and also got problems with the sigma (SIG) to be positive definite.

Have you implemented the csminwel algorithm in the estimation? Which one of those is possible to use would you recommend?

Regards,
Pedro

**Comment by jmaih** [comment]
Hi Pedro,

1. You reached a minimum, not necessarily the "global one", which you cannot prove for the type of models we estimate unless you know it in advance.

1. It is well possible that one optimization procedure reaches a peak different from another one and that is the exact reason why there are many optimization procedures with different strengths and abilities. Sometimes, as it seems to be the case in your example, an optimization procedure may stop before reaching a peak. This can occur because of some discontinuities in the objective function, thin ridges that are difficult to traverse etc. When this occurs, the numerical covariance matrix calculated will in general not be positive definite.

1. csminwel is just one optimization procedure and there is no guarantee that it will always give you the best results in all problems. RISE does not implement csminwel but it is very easy to interface it to RISE.

1. The default optimizer of RISE is Matlab's fmincon but RISE gives you the possibility of using your own optimization procedure. Get help by typing help dsge/estimate and or take a look at issues #12, #13 and #21 where some of those aspects have been discussed.

Cheers,

Junior

**Comment by Kairey** [comment]
Hi,
I know RISE can easily implement csminwel and bee_gate, but both of the optimizers are not appropriate for my models, I wonder how to use other Matlab's optimizers in RISE，such as "Marco Ratto’s newrat" and "Monte-Carlo based optimization routine". 
I haven't found any answers yet, could you help me? Thanks in advance.
Best,
Kairey
