### ISSUE TITLE
Problem in solving regime-switching model

### ISSUE THREAD

**Issue by andrewsun90** [jmaih/RISE_toolbox#41]
Hi Junior,

I was trying to solve a nonlinear medium-scale NK model with switching regimes. If I do not declare `'steady_state_imposed', true`, then the model can only be solved in one of the two regimes using any solver. If I declare this, then the model can be solved using 'mn' or 'mnk' solver, but the solution is unstable.

To summarize, here is what I found in the debug mode:

(1) model with switching regimes + any solver -> the model in one regime is solved, but the model in another regime is not solved because lsqnonlin exceeded the iteration limit (Residual = 1e-9, Lambda = 1e-7 when stopped)

(2) model with switching regimes + regular solver + `'steady_state_imposed', true` --> not solved

(3) model with switching regimes + 'mn' or 'mnk' solver + `'steady_state_imposed', true` --> the model in both regimes are solved, but solution unstable

Would you offer me any advice about how I shall proceed? Thanks!

Best,
Zexi

**Comment by andrewsun90** [comment]
Hi Junior,

I just changed the inflation indexation parameter from 0.5 to 0.4, and the Markov-switching model is solved by either the regular solver or the 'mn' solver. Still, I have no idea why this would happen, and it seems that the IRFs are not exactly the same using different solvers. Can I find anywhere the detailed information of each solver in RISE? Thanks!

Best,
Zexi

**Comment by jmaih** [comment]
Hi Zexi,

It is always better that you tell me what error message you get from the
interface rather than trying to describe the internals. For instance, I do
not remember what Lambda =1e-7 refers to. You could also email me the file
that creates the error so that I can replicate the problem.

   1. what do you mean the model can only be solved in one regime? either
   it solves or it does not, unless you are using the occbin procedure, in
   which case only the reference regime has a solution.
   2. Maybe you are referring to the steady state? In that case, as I said
   before, it would take a course just to go through the various options for
   solving the steady state in RISE.
   3. strictly speaking, solving simply means finding a function
   x_t=T(x_{t-1},e_t) such that Ef(x_{t+1},x_t,x_{t-1},e_t)=0. Nothing
   guarantees that the solution found will be stable.

Cheers,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by jmaih** [comment]
Hi Zexi,

The solution to the problem is not necessarily stable or unique. Different
solution algorithms may find different solutions and different initial
conditions may yield different solutions as well if the problem turns out
to have many solutions.

This paper
<http://www.norges-bank.no/en/Published/Papers/Working-Papers/2015/12015/>
and some of the references therein discuss the various issues related to
solving regime-switching DSGE models.

Cheers,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)
