### ISSUE TITLE
Plot normalized priors and posteriors

### ISSUE THREAD

**Issue by LeonardRW** [jmaih/RISE_toolbox#46]
Hi Junior,

I'm trying to extract the normalized information for my model parameters  after running a MH algorithm.
In the past I used this line to do that: 
[ppdata]=plot_priors_and_posteriors(obj,Results.pop,myparams,'normalize2prior') 

But it seems like the 'normalize2prior' instruction doesn't work anymore. There is another form to obtain this information? 

Many thanks in advance.

Regards,

Leonard

**Comment by jmaih** [comment]
Hi Leonard,

Perhaps you should do

[ppdata]=plot_priors_and_posteriors(obj,Results.pop,myparams,true)

instead of

[ppdata]=plot_priors_and_posteriors(obj,Results.pop,
myparams,'normalize2prior')

Cheers,

Junior


--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by LeonardRW** [comment]
Hi again Junior,

Still not working the option "true".  RISE show the following error:

**
Error using rise_generic/plot_priors_and_posteriors
Too many input arguments.
**

I remmeber that before in the function plot_priors_and_posteriors the argument 'normalize2prior' 
where available. Do you have another guess to solve this problem? 

thanks,

Leonard.

**Comment by jmaih** [comment]
If I could see the problem I would be able to solve it. 

Looks like you are not using the most recent version of RISE. Could that be the issue?
