### ISSUE TITLE
Simulation with specified shock series

### ISSUE THREAD

**Issue by andrewsun90** [jmaih/RISE_toolbox#52]
Hi Junior,

Just a quick question: can RISE run simulation with a user-specified series for exogenous shock?

Cheers,
Zexi

**Comment by jmaih** [comment]
Yes it can, it is simply a conditional forecasting exercise.

Cheers,

J.

**Comment by andrewsun90** [comment]
Thanks Junior, your answer reminded me of the material we went through on course, and the problem is solved there!


Best,
Zexi

**Comment by andrewsun90** [comment]
Hi Junior, after some trial and error I am still not sure whether my conditional forecasting code is correct. For example, suppose I wish to see the response of main variables after a sizeable exogenous shock called `eps_a` realizes in the second period (basically a IRF). According to your tutorial I wrote
`db = initial_conditions(m, 1, 'steady', 1);`
`db.eps_a(1, 1, 1+1) = 10;`
`sim_result = simulate(m, 'simul_historical_data', db,'forecast_cond_exo_vars','eps_a');`

Initially I thought this was the correct way, but then I found the result somewhat confusing, because a shock process called `b`, which is controlled by another exogenous shock `eps_b`, is not at its steady state level. Though the magnitude of the response of `b` to `eps_a` is small (<1e-14), theoretically speaking it should not response at all. So what's wrong with my code?


Cheers,
Zexi

**Comment by jmaih** [comment]
Hi Zexi,

try setting "simul_shock_uncertainty" to false.

Cheers,

J.

**Comment by johannakrenz** [comment]
Sorry to come back to this old post, but I just tried to run a simulation based on three shock series from a previous simulation. So see if everything goes right, I plotted the results from the two subsequent simulations mysims and mysims2, obtained from:
mysims=simulate(m,'simul_honor_constraints',true,'simul_periods',300);
and 
mysims2=simulate(m, 'simul_honor_constraints',true,'simul_periods',300,'forecast_cond_exo_vars',{'e_a','e_ksi','e_r'},'simul_shock_uncertainty',false);
where e_a, e_ksi, e_r are the three shocks of the model.
However, the plots look completely different and I wonder why? They should start from the same point (The documentation says: "If empty, the simulations start at the steady state.") Maybe I'm misunderstanding something?

**Comment by jmaih** [comment]
Hi Johanna,

Few things to think about:

Is the model switching? If so in order to replicate the simulation you also
need to condition on the regime

Also, I cannot see that you gave a database from which the conditioning
information is to be obtained.

Finally, it is important to know what the initial conditions are. When
simulating for the first time. did you allow for a burnin period?

J.

**Comment by jkrenz** [comment]
Hi Junior, 

**To your 2. question:** "Also, I cannot see that you gave a database from which the conditioning
information is to be obtained.": I just wrote everything into one driver-file, just to see if it works. So the conditioning info comes from the first simulation and it is in the workspace.

**To your 1. question:** Yes, the model is (endogenously) switching. I had a look into the simulate.m file from the RISE toolbox. There, it reads _"**simul_historical_data** contains the historical data as well as conditional information over the forecast horizon. It may also includeas an alternative to **simul_regime**, a time series with name **regime**, which indicates the regimes over the forecast horizon."_ So, therefore, I know write the first simulation command as before as

mysims=simulate(m,'simul_honor_constraints',true,'simul_periods',300); 

and the second as

regime=mysims.regime; %if I don't define "regime" RISE does not find "regime"
mysims2=simulate(m,'simul_historical_data',regime,'simul_periods',nosimul,'forecast_cond_exo_vars',{'e_a','e_ksi','e_r'},'simul_shock_uncertainty',false);

However, now apparently RISE cannot find the shock processes any more, as it states "locate_variables:: variable e_a not found" and this error message apparently comes in via initial_conditions (Error in generic/set_simulation_initial_conditions) which I don't understand, because I don't want to give specific initial conditions. 

I tried to define 
e_a=mysims.e_a.data;
e_ksi=mysims.e_ksi.data;
e_r=mysims.e_r.data;
before the second simulation, but it does not work either. RISE also complains that it cannot find the variable

**To your 3. questions:** I did not specifiy a burnin period in the first simulation. Is there a positive number of burn in periods by default, or does this mean that I have zero burn in periods?

I have one additional questions: I don't see that the argument simul_to_time_series changes anything. With or without this command, mysims contains a buch of time series. 

Thank you very much in advance. 
Best, Johanna

**Comment by jkrenz** [comment]
Good morning, 

we figured out how to do it, i.e., to get exactly the same simulation twice: 

    nosimul=300;
    mysims=simulate(m,'simul_honor_constraints',true,'simul_periods',nosimul,'simul_burn',0); %with 'simul_burn',0, mysims will include the steady state (i.e. all shocks are zero) in the first period

    db = initial_conditions(m, 1, 'steady', 1);

    % set initial conditions for shocks
    db.e_a(1, 1, 1:301)  = mysims.e_a.data;
    db.e_ksi(1, 1, 1:301)  = mysims.e_ksi.data;
    db.e_r(1, 1, 1:301)  = mysims.e_r.data;

    % specify active shocks
    shocks = {'e_a','e_ksi','e_r'};

    % set initial conditions for regime
    % create the field db.regime; by copying db.e_r to it it will have the right
    % character (ts); if the first step is omitted, db.regime will have the
    % character double and the next simulation does not run
    db.regime = db.e_r; 
    db.regime(1, 1, 1:301)=mysims.regime.data;

mysims2=simulate(m,'simul_honor_constraints',true,'simul_historical_data',db,'simul_periods',nosimul,'forecast_cond_exo_vars',shocks,'simul_shock_uncertainty',false);

I know, it doesn't give us any new insights to have the same simulation results twice, but we needed to understand how this works in order to get some other information from the simulations and in order to be able to compare the results of different simulations. 

Our last question, however, remains: Is the command simul_to_time_series outdated? We can't see how it changes the output of the simulation.

Best and thanks again for your help!

**Comment by jmaih** [comment]
Hi Johanna,

simul_to_time_series  was used to give the option to store simulations
either as time series or as a matrix. The option is deprecated now.

Keep up the good work, I look forward to seeing the results.

Cheers,

J.

**Comment by jkrenz** [comment]
Thanks for the clarification!
