### ISSUE TITLE
Some questions on simulations with RISE

### ISSUE THREAD

**Issue by leonardabagnale** [jmaih/RISE_toolbox#57]
Hi Junior!
I have some questions about doing conditional forecasting. 
Please correct me if I am wrong. When I use the forecast command plus the option simul, for example: ('simul_regime',2'forecast_cond_exo_vars',{'ea'}), RISE simulate regime 2 using the conditional shock ea (the expected series for the shock generated by RISE) assuming that only regime 2 exists in the system. 
So, the questions are:
1)	Is it possible to generate a conditional forecast without assuming that only the simulated regime exists? A way of introduce a modification in the agens’ beliefs. For example, a simulation that introduce that the agents do not belief that, after a specific date the system would return to the initial regime. 
To do that I was thinking in conditioning on the shocks  (ea for this case, using the expected series) and smoothed probabilities (modifying the probabilities for the regime that would not occur in the future to 0 an to 1 to the other). It is the right way to implement this exercise in RISE?
2)	This is may be a simple question. After completing a metropolis hasting algorithm, does RISE have a function to update the final parameters (for example at the mean) in the object that contain the estimation information? 
This is to do the simulations once I have the MH estimated parameters. 

Best regards,

Leonard

**Comment by jmaih** [comment]
Hi Leo,


   1. If you do not condition on a particular regime, the process will jump
   randomly from one regime to another and you will still get your conditional
   forecast. This assumes that there is a non-zero probability of visiting the
   regimes the process jumps to. To do this you just have to NOT provide any
   information about the regime, i.e. replace
('simul_regime',2,'forecast_cond_exo_vars',{'ea'})
   with  ('forecast_cond_exo_vars',{'ea'}). But then because the
   conditional forecast will be different every time you run it, if you are
   interested in the mean of the forecast, you will have to repeat the
   exercise several times and take the average. The other thing you can do is
   to change the probabilities as you are suggesting. But then notice that the
   solution of the model will also change accordingly. RISE is flexible enough
   to accommodate all those possibilities.
   2. Check the method "draw_parameter". The syntax
   is [draw1,m1]=draw_parameter(m0,simulation_folder). It takes as inputs the
   model object (m0), the simulations or the location of the simulations
   (simulation_folder) and returns a parameter draw (draw1) and an updated
   model object parameterized with the parameter draw (m1). You can then run
   any simulation you like using m1.

Cheers,

Junior

--
"You can never know everything", Lan said quietly, "and part of what you
know is always wrong. Perhaps even the most important part. A portion of
wisdom lies in knowing that. A portion of courage lies in going on anyway."
Robert Jordan, Winter's Heart, Book IX of the Wheel of Time.

We have not succeeded in answering all of our problems. The answers we have
found only serve to raise a whole set of new issues. In some ways we are as
confused as ever, but we believe we are confused on a higher level and
about more important things. (cited in Øksendal, 1985)

**Comment by leonardabagnale** [comment]
Many thanks for your response, Junior.

a. I have an additional question. For (1.) If I decide to change the smoothed probabilities (for certain dates of the sample), given that the "filtered_state_probabilities" of the RISE object have the read-only property , and that the smoothed probabilities does not enter as endogenous or exogenous variables in the model, what would be the way to modify these series?
Additionally, If I modify the smoothed probabilities of each state I will ahve different series for the expected_smoothed_variables of the model. So, after a. step is completed, do I have to filter the model using my observable series and the new smoothed probabilities to do the conditional forecasting excercise? Am I right? or can I use the expected shocks (weighted) and RISE re-adjust this one with the new probabilities?

Cheers,

Leonard.A.

**Comment by jmaih** [comment]
Hi Leo,

I do not understand why you would want to modify the output of the procedure. Of course you can always extract the data from the model object and use them as you like but there is a reason why some parts of the model object are not meant to be modified. 

The transition probabilities are the result of a filtering algorithm in which other quantities are also estimated.

Maybe I'm missing something?

Cheers

Junior

**Comment by leonardabagnale** [comment]
Hi Junior,

Let me explain my point more clearly. I don't want to modify the output of the procedure itself. What I would like to do is some simulations, like counterfactuals,using the conditional forecasting function. 
I understand how to do it using the expected variables in a multiple regime model and conditioning or not in those regimes. 
But I was wondering if is it possible to condition the model in the output of the procedure, specifically in the smoothed probabilities, just to simulate, for example that, given that there are two regimes, after 2000q1 the probability of being in regime 1 is close to 0 (introducing the fact that agents doesn't belief that the system would return to this regime). 
As I said earlier, I understand that, for example the output of the expected variables (weigthed by the smoothed probabilities) would differ from the main procedure. Is it possible to implement that in RISE?
Many thanks for your time and responses.

Regards,

Leonard

**Comment by jmaih** [comment]
Hi Leo,

I do not understand what you mean by "condition the model in the output of
the procedure". Basically the conditional forecasting routine will have as
inputs

   1. a model object,
   2. some initial conditions,
   3. some conditioning information, which in general would be a mix of
   endogenous variables, exogenous variables and regimes

Those three things can be completely disconnected and come from different
sources but the key is that the information they convey should be
consistent. In other words, the initial conditions and the condition
information should be about variables that the model object recognizes.

We do not condition on the smoothed probabilities (of being in some
regime), we condition on the regimes directly.

Cheers,

Junior

>

**Comment by leonardabagnale** [comment]
Junior,
Many thanks for your explanation. It helped me alot to clarify.
Best regards,
Leonard.
