### ISSUE TITLE
Question about transition probabilities

### ISSUE THREAD

**Issue by zhuzixiang** [jmaih/RISE_toolbox#61]
Dear Junior,
One of the referees asked me how the endogenous transition probabilities are achieved. Specifically, how the transition probabilities are estimated. It seems in .dsge or .rs we treat them as other estimated parameters. I check the formula in your working paper "Efficient Perturbation Methods for Solving Regime-Switching DSGE Models" and want to figure out which formulas correspond to the estimation of transition probabilities. However, I still get lost about how to estimate the transition probabilities technically. I wish you could clarify this to me.
Thanks.
Best!
Zixiang Zhu

**Comment by jmaih** [comment]
Hi Zixiang,

Good to hear from you. The probabilities can be either

   - constant, in which case they are simple parameters,
   - or time varying, in which case they are a function of both parameters
   and variables.

RISE estimates parameters and does not make a distinction between the
parameters affecting the transition probabilities, the scales on shock
variables (which would be standard deviations in other software) or the
more (deep) structural parameters.

It turns out that the parameters that enter the transition probabilities do
affect the solution of the model and therefore the likelihood function. The
transition probabilities (time-varying or not) also affect the computation
of the likelihood above and beyond the indirect effect via the solution.

In the paper you are referring to, to simplify the exposition, the
transition probabilities are merged with the equations of the system. This
can be done since in the original system (first equation on page 7) the
probabilities multiply the equations.

Cheers,

Junior

>

**Comment by zhuzixiang** [comment]
Thanks a lot  and you're always so kind!:)
