### ISSUE TITLE
Problem with estimation

### ISSUE THREAD

**Issue by Alexfjs** [jmaih/RISE_toolbox#72]
Dear Junior,

I am writing for two specific questions. When I estimate a Markov Switching DSGE and I have to declare the parameterization within the .rs file, I understand that I must declare:

parameter_name, initial value, lower bound, upper bound, distribution.

I have a parameter that has an inverse_gamma distribution with an initial value of 15, the lower bound and upper bound are 12.0364 and 18.5516 respectively. The problem is that when I run the file, RISE I get an error:

prior_setting_engine (GENTLE WARNING) :: upper bound of inverse gamma distribution truncated at 10
Error using utils.prior.prior_setting_engine (line 99)
prior_setting_engine :: parameter SIGMA_EPS_P_CM_vol_2 (15) outside its bounds [7.11883
10]

Second, how can I force the parameter to move between two specific numbers?

Beforehand

Thank you very much

**Comment by jmaih** [comment]
Hi Alex,

The inverse gamma distribution will be changed at some point and then those
restrictions will be removed.

Now, that distribution is often chosen to push the estimated parameter
towards low values i.e. towards zero. If you really believe that the
parameter should assume values as big as 18 or more, one way to get around
the restriction imposed by RISE is to scale the parameter. Concretely,
suppose your parameter is alpha. Then we can always write

alpha=10*alphax

As you can see, if alpha is 18 then alphax is 1.8. Therefore if you put the
inverse gamma distribution on alphax rather than alpha, you will go around
the restrictions of RISE. Just remember to divide the original bounds by 10
as well.

Cheers,

Junior

**Comment by Alexfjs** [comment]
Thank you very much Junior


Cheers

Alex
