### ISSUE TITLE
Time-dependent transition probability

### ISSUE THREAD

**Issue by p1m3nt** [jmaih/RISE_toolbox#76]
Hi Junior, 

is it possible to do a time-dependent transition probability model in RISE? Say, in a 2-regime switch setup, the transition probability of regime 1 increases over time as the probability of regime 2 decreases accordingly?  Thank you very much in advance.

Peter

**Comment by jmaih** [comment]
Hi Peter,

There is no explicit provision for expressing transition probabilities as a
function of time. But RISE is flexible enough to allow for such a behavior
at least in the DSGE context and so long as you know how to write the
process that governs the evolution of transition probabilities.

The way to implement what you have in mind is to first declare the variable
that will hold time as an exogenous variable. The variable also needs to be
declared as an observable variable in order to differentiate it from other
exogenous variables. Once that is done the variable can be used.

Cheers,

Junior

**Comment by p1m3nt** [comment]
Hi Junior,
thank you for the explanation, I'll try that. 
Another question, in a user defined transition probability function, when I tried to use the if-else logical structure, I got "Conversion to logical from splanar is not possible." What am I doing wrong here?
Thanks again.
Peter

**Comment by jmaih** [comment]
Hi Peter,

I do not understand exactly what you are doing. But whatever you put in the
transition probabilities has to be differentiated. If-else type of
statements evaluate to logical and RISE doesn't seem to able to deal with
probabilities involving logicals.

Cheers,

Junior

**Comment by p1m3nt** [comment]
Hi Junior,

Sorry for the confusion and what I'm trying to do is to define a transition probability function that does something like:

function [p] = transition_probability(endo)
if endo>a_threshold
p=some_cdf(endo)
else
p=some_other_cdf(endo)
end
end

Thanks.

Peter

**Comment by jmaih** [comment]
Hi Peter,

RISE does not know how to differentiate such functions. You may want to try
changing the type of derivatives.

Try one of the following

'solve_derivatives_type','automatic'

'solve_derivatives_type','numerical'

The second one is more likely to work but would not give as precise results
as the first one.

Cheers,

Junior

**Comment by p1m3nt** [comment]
Hi Junior,

thanks very much. I've put the arguments you suggested into rise(), but unfortunately I still get the same error.  

I find that things put into the external probability function are 'splanar' object, and 'splanar' seems to have a 'if_elseif' method, does this have anything to do with problem and somehow could this be used to solve the logical coversion issue? Thanks.

Peter

**Comment by jmaih** [comment]
Would you mind sending me your files (at my private email address) so that I can replicate the error and see whether there is a workaround?
